services:
    App\ServiceInterface\Inventory\InventoryServiceInterface: '@App\Service\Inventory\InMemoryInventoryService'
    App\ServiceInterface\Payment\PaymentGatewayInterface: '@App\Service\Payment\StripeGateway'
    App\ServiceInterface\Shipment\CarrierInterface: '@App\Service\Shipment\UPSCarrier'
