services:
  App\Strategy\Order\DefaultTaxationStrategy: ~
  App\Strategy\Order\DefaultPromotionStrategy: ~

  App\Service\Order\OrderPricingService:
    arguments:
      - '@App\Strategy\Order\DefaultPromotionStrategy'
      - '@App\Strategy\Order\DefaultTaxationStrategy'

  App\Message\Handler\Order\RecalculateOrderPricingHandler:
    tags: ['messenger.message_handler']