services:
    App\Ordering\ServiceInterface\Inventory\InventoryServiceInterface: '@App\Ordering\Service\Inventory\InMemoryInventoryService'
    App\Ordering\ServiceInterface\Payment\PaymentGatewayInterface: '@App\Ordering\Service\Payment\StripeGateway'
    App\Ordering\ServiceInterface\Shipment\CarrierInterface: '@App\Ordering\Service\Shipment\UPSCarrier'
