doctrine:
    dbal:
        url: '%env(resolve:PLATFORM_DATA_DATABASE)%'
    orm:
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/Order'
                prefix: 'App\Ordering\Entity\Order'
                alias: Order
            Objecting:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                prefix: 'App\Objecting\Embeddable'
                alias: Objecting
