doctrine:
  orm:
    mappings:
      OrderMetricsRollup:
        is_bundle: false
        type: attribute
        dir: "%kernel.project_dir%/src/Service/Order"
        prefix: "App\Service\Order"
        alias: OrderMetricsRollup
