framework:
    secret: 'testsecret'
    test: true
    http_method_override: false
    csrf_protection: true
    form: true
    validation:
        enable_attributes: true
    session:
        enabled: true
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        utf8: true
