
monolog:
  channels: ['order.audit.ndjson']

  handlers:
    order_audit_ndjson:
      type: stream
      path: '%kernel.logs_dir%/order-audit-ndjson.log'
      level: info
      channels: ['order.audit.ndjson']
