services:
  App\Service\Order\Outbox\DlqService:
    autowire: true
    autoconfigure: true

  App\ServiceInterface\Order\Outbox\DlqServiceInterface: '@App\Service\Order\Outbox\DlqService'

  App\Controller\Order\DlqController:
    autowire: true
    autoconfigure: true
