apiVersion: apps/v1
kind: Deployment
metadata: { name: pushgateway }
spec:
    replicas: 1
    selector: { matchLabels: { app: pushgateway } }
    template:
        metadata: { labels: { app: pushgateway } }
        spec:
            containers:
                -   name: pushgateway
                    image: { { .Values.pushgateway.image } }
                    securityContext:
                        allowPrivilegeEscalation: false
                        runAsNonRoot: true
                        runAsUser: 65534
                    ports: [ { containerPort: 9091 } ]
