<?php

declare(strict_types=1);

namespace App\Ordering\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915180000CurrentBaseline extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Materialize the current Ordering ORM baseline for missing Ordering-owned tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Ordering baseline supports PostgreSQL only.');
        $tables = [
            'analytics_records',
            'idempotency_key',
            'inventory_reservation',
            'order_archive',
            'order_audit_log',
            'order_dead_letter_projection',
            'order_dispute',
            'order_event_record',
            'order_item',
            'order_log',
            'order_metrics_export_log',
            'order_metrics_projection',
            'order_payment',
            'order_payment_allocation',
            'order_payment_transaction',
            'order_payment_translation',
            'order_price_audit',
            'order_provider_route',
            'order_refund',
            'order_refund_transaction',
            'order_return_policy',
            'order_security_key',
            'order_shipment',
            'order_shipment_item',
            'order_shipment_translation',
            'order_shipment_view',
            'order_status',
            'order_status_history',
            'order_stock_reservation',
            'order_storage',
            'order_taxation_audit',
            'outbox_messages',
            'webhook_log',
        ];
        $existing = array_values(array_filter($tables, static fn (string $table): bool => $schema->hasTable($table)));
        if (count($existing) === count($tables)) { return; }
        $this->abortIf([] !== $existing, sprintf('Partial Ordering baseline detected (%d/%d tables); refusing mixed create/adopt execution.', count($existing), count($tables)));

        $this->addSql('CREATE TABLE analytics_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) NOT NULL, order_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_archive (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(100) DEFAULT NULL, archived_reason VARCHAR(255) DEFAULT NULL, snapshot JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2386F4D7D17F50A6 ON order_archive (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2386F4D7989D9B62 ON order_archive (slug)');
        $this->addSql('CREATE TABLE order_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_type VARCHAR(24) NOT NULL, actor_id VARCHAR(64) DEFAULT NULL, action VARCHAR(64) NOT NULL, subject_type VARCHAR(64) DEFAULT NULL, subject_id VARCHAR(64) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, payload JSON DEFAULT NULL, hash VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_dead_letter_projection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id VARCHAR(128) DEFAULT NULL, message_class VARCHAR(255) DEFAULT NULL, reason TEXT DEFAULT NULL, payload JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4B35F19D17F50A6 ON order_dead_letter_projection (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4B35F19989D9B62 ON order_dead_letter_projection (slug)');
        $this->addSql('CREATE TABLE order_dispute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) NOT NULL, reason VARCHAR(255) DEFAULT NULL, external_id VARCHAR(128) DEFAULT NULL, status VARCHAR(32) NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAE8F94C8D9F6D38 ON order_dispute (order_id)');
        $this->addSql('CREATE TABLE order_event_record (event_id VARCHAR(64) NOT NULL, order_id VARCHAR(64) NOT NULL, event_name VARCHAR(128) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (event_id))');
        $this->addSql('CREATE TABLE idempotency_key (key VARCHAR(128) NOT NULL, scope VARCHAR(128) DEFAULT NULL, key_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (key))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FD1C14757BFB971 ON idempotency_key (key_hash)');
        $this->addSql('CREATE TABLE inventory_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id VARCHAR(64) NOT NULL, reservation_key VARCHAR(128) NOT NULL, lines JSON NOT NULL, state VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_363A759ADF928676 ON inventory_reservation (reservation_key)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(128) NOT NULL, quantity INT NOT NULL, base_price NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, discount INT DEFAULT 0 NOT NULL, tax INT DEFAULT 0 NOT NULL, final_price INT DEFAULT 0 NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('CREATE TABLE order_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_status_code VARCHAR(64) NOT NULL, comment TEXT DEFAULT NULL, customer_notified BOOLEAN DEFAULT false NOT NULL, o_hash VARCHAR(64) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, order_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC6427A5D17F50A6 ON order_log (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC6427A5989D9B62 ON order_log (slug)');
        $this->addSql('CREATE INDEX IDX_CC6427A58D9F6D38 ON order_log (order_id)');
        $this->addSql('CREATE TABLE order_metrics_export_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, export_key VARCHAR(128) DEFAULT NULL, target VARCHAR(128) DEFAULT NULL, status VARCHAR(64) DEFAULT NULL, payload JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8083F77DD17F50A6 ON order_metrics_export_log (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8083F77D989D9B62 ON order_metrics_export_log (slug)');
        $this->addSql('CREATE TABLE order_metrics_projection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, orders_count INT DEFAULT 0 NOT NULL, gross_total NUMERIC(20, 2) DEFAULT \'0.00\' NOT NULL, refund_total NUMERIC(20, 2) DEFAULT \'0.00\' NOT NULL, net_total NUMERIC(20, 2) DEFAULT \'0.00\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_omp_date ON order_metrics_projection (date)');
        $this->addSql('CREATE TABLE outbox_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, aggregate_id VARCHAR(64) NOT NULL, event_type VARCHAR(128) NOT NULL, payload TEXT NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dispatched BOOLEAN DEFAULT false NOT NULL, dispatched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, attempts INT DEFAULT 0 NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24F454FE989D9B62 ON outbox_messages (slug)');
        $this->addSql('CREATE TABLE order_payment_allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, payment_id INT NOT NULL, order_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_951F49C94C3A3BB ON order_payment_allocation (payment_id)');
        $this->addSql('CREATE INDEX IDX_951F49C9E415FB15 ON order_payment_allocation (order_item_id)');
        $this->addSql('CREATE TABLE order_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gateway VARCHAR(32) NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, external_ref VARCHAR(64) DEFAULT NULL, is_partial BOOLEAN NOT NULL, status VARCHAR(32) NOT NULL, refunded_amount NUMERIC(12, 2) NOT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B522D46B445906B ON order_payment (external_ref)');
        $this->addSql('CREATE INDEX IDX_9B522D468D9F6D38 ON order_payment (order_id)');
        $this->addSql('CREATE TABLE order_payment_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, order_id VARCHAR(64) NOT NULL, amount NUMERIC(12, 2) NOT NULL, method VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, tx_id VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4BFDED79989D9B62 ON order_payment_transaction (slug)');
        $this->addSql('CREATE TABLE order_payment_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, locale VARCHAR(16) NOT NULL, timezone VARCHAR(64) NOT NULL, order_payment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8DA3ADC7D17F50A6 ON order_payment_translation (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8DA3ADC7989D9B62 ON order_payment_translation (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_payment_translation_locale ON order_payment_translation (order_payment_id, locale)');
        $this->addSql('CREATE INDEX IDX_8DA3ADC7B7195EEE ON order_payment_translation (order_payment_id)');
        $this->addSql('CREATE TABLE order_price_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(100) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, subtotal NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, discount_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, tax_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, grand_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, payload JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A263889FD17F50A6 ON order_price_audit (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A263889F989D9B62 ON order_price_audit (slug)');
        $this->addSql('CREATE TABLE order_provider_route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_key VARCHAR(128) DEFAULT NULL, route_key VARCHAR(128) DEFAULT NULL, enabled BOOLEAN DEFAULT false NOT NULL, metadata JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33E245BDD17F50A6 ON order_provider_route (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33E245BD989D9B62 ON order_provider_route (slug)');
        $this->addSql('CREATE TABLE order_refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, reason VARCHAR(128) DEFAULT NULL, is_partial BOOLEAN NOT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98A3048D8D9F6D38 ON order_refund (order_id)');
        $this->addSql('CREATE TABLE order_refund_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, order_id VARCHAR(64) NOT NULL, refund_id VARCHAR(64) NOT NULL, payment_ref VARCHAR(128) DEFAULT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, reason VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5119FB57989D9B62 ON order_refund_transaction (slug)');
        $this->addSql('CREATE TABLE order_return_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) DEFAULT NULL, nameEntity VARCHAR(255) DEFAULT NULL, return_window_days INT DEFAULT 0 NOT NULL, description TEXT DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19C3D71BD17F50A6 ON order_return_policy (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19C3D71B989D9B62 ON order_return_policy (slug)');
        $this->addSql('CREATE TABLE order_security_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_id VARCHAR(128) DEFAULT NULL, algorithm VARCHAR(64) DEFAULT NULL, public_key TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF333D6FD17F50A6 ON order_security_key (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF333D6F989D9B62 ON order_security_key (slug)');
        $this->addSql('CREATE TABLE order_shipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, carrier VARCHAR(24) NOT NULL, tracking_code VARCHAR(64) DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, status VARCHAR(24) NOT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E333C26D8D9F6D38 ON order_shipment (order_id)');
        $this->addSql('CREATE TABLE order_shipment_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, shipment_id INT NOT NULL, order_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ACA63B927BE036FC ON order_shipment_item (shipment_id)');
        $this->addSql('CREATE INDEX IDX_ACA63B92E415FB15 ON order_shipment_item (order_item_id)');
        $this->addSql('CREATE TABLE order_shipment_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, locale VARCHAR(16) NOT NULL, timezone VARCHAR(64) NOT NULL, order_shipment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25938BD3D17F50A6 ON order_shipment_translation (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25938BD3989D9B62 ON order_shipment_translation (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_shipment_translation_locale ON order_shipment_translation (order_shipment_id, locale)');
        $this->addSql('CREATE INDEX IDX_25938BD36052497A ON order_shipment_translation (order_shipment_id)');
        $this->addSql('CREATE TABLE order_shipment_view (order_id VARCHAR(64) NOT NULL, carrier VARCHAR(64) NOT NULL, tracking VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (order_id))');
        $this->addSql('CREATE TABLE order_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_status_code VARCHAR(64) NOT NULL, order_status_name VARCHAR(255) DEFAULT NULL, order_status_color VARCHAR(64) DEFAULT NULL, order_status_description TEXT DEFAULT NULL, order_stock_handle VARCHAR(16) DEFAULT \'A\' NOT NULL, ordering INT DEFAULT 0 NOT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B88F75C954A1E28A ON order_status (order_status_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B88F75C9D17F50A6 ON order_status (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B88F75C9989D9B62 ON order_status (slug)');
        $this->addSql('CREATE TABLE order_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, previous_status VARCHAR(32) NOT NULL, new_status VARCHAR(32) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, storage_order_id INT DEFAULT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_471AD77E2E54517F ON order_status_history (storage_order_id)');
        $this->addSql('CREATE INDEX IDX_471AD77E8D9F6D38 ON order_status_history (order_id)');
        $this->addSql('CREATE TABLE order_stock_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id VARCHAR(64) NOT NULL, sku VARCHAR(64) NOT NULL, quantity INT NOT NULL, status VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_storage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(100) DEFAULT NULL, vendor_id VARCHAR(64) DEFAULT NULL, billing_address_id VARCHAR(64) DEFAULT NULL, shipment_address_id VARCHAR(64) DEFAULT NULL, currency VARCHAR(3) NOT NULL, subtotal NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, discount_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, tax_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, shipment_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, paid_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, order_status_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A200B27F551F0F81 ON order_storage (order_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A200B27FD17F50A6 ON order_storage (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A200B27F989D9B62 ON order_storage (slug)');
        $this->addSql('CREATE INDEX IDX_A200B27FD7707B45 ON order_storage (order_status_id)');
        $this->addSql('CREATE TABLE order_taxation_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(100) DEFAULT NULL, tax_provider VARCHAR(100) DEFAULT NULL, tax_total NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, payload JSON DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EB30DF4D17F50A6 ON order_taxation_audit (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EB30DF4989D9B62 ON order_taxation_audit (slug)');
        $this->addSql('CREATE TABLE webhook_log (key VARCHAR(128) NOT NULL, event_type VARCHAR(128) NOT NULL, payload TEXT NOT NULL, PRIMARY KEY (key))');
        $this->addSql('ALTER TABLE order_dispute ADD CONSTRAINT FK_CAE8F94C8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_log ADD CONSTRAINT FK_CC6427A58D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_payment_allocation ADD CONSTRAINT FK_951F49C94C3A3BB FOREIGN KEY (payment_id) REFERENCES order_payment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_payment_allocation ADD CONSTRAINT FK_951F49C9E415FB15 FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_payment ADD CONSTRAINT FK_9B522D468D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_payment_translation ADD CONSTRAINT FK_8DA3ADC7B7195EEE FOREIGN KEY (order_payment_id) REFERENCES order_payment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_refund ADD CONSTRAINT FK_98A3048D8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_shipment ADD CONSTRAINT FK_E333C26D8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_shipment_item ADD CONSTRAINT FK_ACA63B927BE036FC FOREIGN KEY (shipment_id) REFERENCES order_shipment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_shipment_item ADD CONSTRAINT FK_ACA63B92E415FB15 FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_shipment_translation ADD CONSTRAINT FK_25938BD36052497A FOREIGN KEY (order_shipment_id) REFERENCES order_shipment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E2E54517F FOREIGN KEY (storage_order_id) REFERENCES order_storage (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_storage ADD CONSTRAINT FK_A200B27FD7707B45 FOREIGN KEY (order_status_id) REFERENCES order_status (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Current Ordering ORM baseline is the forward schema contract.');
    }
}
