order_controller:
    resource: ../src/Controller/OrderController.php
    type: attribute

order_management_controller:
    resource: ../src/Controller/OrderManagementController.php
    type: attribute

order_host_health_check_controller:
    resource: ../src/Controller/Monitoring/OrderHostHealthCheckController.php
    type: attribute

order_readiness_controller:
    resource: ../src/Controller/Monitoring/OrderReadinessController.php
    type: attribute

order_metrics_controller:
    resource: ../src/Controller/Monitoring/OrderMetricsController.php
    type: attribute

order_api_controller:
    resource: ../src/Controller/OrderApiController.php
    type: attribute

test_email_controller:
    resource: ../src/Controller/TestEmailController.php
    type: attribute

payment_webhook_controller:
    resource: ../src/Controller/Webhook/PaymentWebhookController.php
    type: attribute

order_monitoring_health_controller:
    resource: ../src/Controller/Monitoring/OrderHealthMonitoringController.php
    type: attribute

cruding_routes:
    resource: ../../Cruding/config/routes/cruding_crud.yaml
