services:
    App\Ordering\OpenApi\OrderOpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments:
            - '@App\Ordering\OpenApi\OrderOpenApiFactory.inner'
        autoconfigure: true
        autowire: true
