services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Ordering\Form\Config\:
    resource: '../../src/Form/Config/'

  App\Ordering\Service\Config\OrderingRateLimitsConfigService:
    arguments:
      $projectDir: '%kernel.project_dir%'
      $applyService: '@App\Administering\Service\Config\AdministrationConfigApplyService'
      $fileWriter: '@App\Administering\Service\Config\AdministrationConfigFileWriterService'
    tags: ['administering.config_tool']
